# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    - cron: '*/3 * * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/675927fdafa2740dd25c5fae
